/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BoldIcon {
    }
    interface DjangoMarkdownField {
        "field_name": string;
        /**
          * @default ''
         */
        "markdown": string;
    }
    interface H1Icon {
    }
    interface H2Icon {
    }
    interface H3Icon {
    }
    interface H4Icon {
    }
    interface H5Icon {
    }
    interface H6Icon {
    }
    interface ItalicIcon {
    }
    interface LinkIcon {
    }
    interface ListIcon {
    }
    interface ListOrderedIcon {
    }
    interface UnderlineIcon {
    }
}
declare global {
    interface HTMLBoldIconElement extends Components.BoldIcon, HTMLStencilElement {
    }
    var HTMLBoldIconElement: {
        prototype: HTMLBoldIconElement;
        new (): HTMLBoldIconElement;
    };
    interface HTMLDjangoMarkdownFieldElement extends Components.DjangoMarkdownField, HTMLStencilElement {
    }
    var HTMLDjangoMarkdownFieldElement: {
        prototype: HTMLDjangoMarkdownFieldElement;
        new (): HTMLDjangoMarkdownFieldElement;
    };
    interface HTMLH1IconElement extends Components.H1Icon, HTMLStencilElement {
    }
    var HTMLH1IconElement: {
        prototype: HTMLH1IconElement;
        new (): HTMLH1IconElement;
    };
    interface HTMLH2IconElement extends Components.H2Icon, HTMLStencilElement {
    }
    var HTMLH2IconElement: {
        prototype: HTMLH2IconElement;
        new (): HTMLH2IconElement;
    };
    interface HTMLH3IconElement extends Components.H3Icon, HTMLStencilElement {
    }
    var HTMLH3IconElement: {
        prototype: HTMLH3IconElement;
        new (): HTMLH3IconElement;
    };
    interface HTMLH4IconElement extends Components.H4Icon, HTMLStencilElement {
    }
    var HTMLH4IconElement: {
        prototype: HTMLH4IconElement;
        new (): HTMLH4IconElement;
    };
    interface HTMLH5IconElement extends Components.H5Icon, HTMLStencilElement {
    }
    var HTMLH5IconElement: {
        prototype: HTMLH5IconElement;
        new (): HTMLH5IconElement;
    };
    interface HTMLH6IconElement extends Components.H6Icon, HTMLStencilElement {
    }
    var HTMLH6IconElement: {
        prototype: HTMLH6IconElement;
        new (): HTMLH6IconElement;
    };
    interface HTMLItalicIconElement extends Components.ItalicIcon, HTMLStencilElement {
    }
    var HTMLItalicIconElement: {
        prototype: HTMLItalicIconElement;
        new (): HTMLItalicIconElement;
    };
    interface HTMLLinkIconElement extends Components.LinkIcon, HTMLStencilElement {
    }
    var HTMLLinkIconElement: {
        prototype: HTMLLinkIconElement;
        new (): HTMLLinkIconElement;
    };
    interface HTMLListIconElement extends Components.ListIcon, HTMLStencilElement {
    }
    var HTMLListIconElement: {
        prototype: HTMLListIconElement;
        new (): HTMLListIconElement;
    };
    interface HTMLListOrderedIconElement extends Components.ListOrderedIcon, HTMLStencilElement {
    }
    var HTMLListOrderedIconElement: {
        prototype: HTMLListOrderedIconElement;
        new (): HTMLListOrderedIconElement;
    };
    interface HTMLUnderlineIconElement extends Components.UnderlineIcon, HTMLStencilElement {
    }
    var HTMLUnderlineIconElement: {
        prototype: HTMLUnderlineIconElement;
        new (): HTMLUnderlineIconElement;
    };
    interface HTMLElementTagNameMap {
        "bold-icon": HTMLBoldIconElement;
        "django-markdown-field": HTMLDjangoMarkdownFieldElement;
        "h1-icon": HTMLH1IconElement;
        "h2-icon": HTMLH2IconElement;
        "h3-icon": HTMLH3IconElement;
        "h4-icon": HTMLH4IconElement;
        "h5-icon": HTMLH5IconElement;
        "h6-icon": HTMLH6IconElement;
        "italic-icon": HTMLItalicIconElement;
        "link-icon": HTMLLinkIconElement;
        "list-icon": HTMLListIconElement;
        "list-ordered-icon": HTMLListOrderedIconElement;
        "underline-icon": HTMLUnderlineIconElement;
    }
}
declare namespace LocalJSX {
    interface BoldIcon {
    }
    interface DjangoMarkdownField {
        "field_name": string;
        /**
          * @default ''
         */
        "markdown"?: string;
    }
    interface H1Icon {
    }
    interface H2Icon {
    }
    interface H3Icon {
    }
    interface H4Icon {
    }
    interface H5Icon {
    }
    interface H6Icon {
    }
    interface ItalicIcon {
    }
    interface LinkIcon {
    }
    interface ListIcon {
    }
    interface ListOrderedIcon {
    }
    interface UnderlineIcon {
    }
    interface IntrinsicElements {
        "bold-icon": BoldIcon;
        "django-markdown-field": DjangoMarkdownField;
        "h1-icon": H1Icon;
        "h2-icon": H2Icon;
        "h3-icon": H3Icon;
        "h4-icon": H4Icon;
        "h5-icon": H5Icon;
        "h6-icon": H6Icon;
        "italic-icon": ItalicIcon;
        "link-icon": LinkIcon;
        "list-icon": ListIcon;
        "list-ordered-icon": ListOrderedIcon;
        "underline-icon": UnderlineIcon;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bold-icon": LocalJSX.BoldIcon & JSXBase.HTMLAttributes<HTMLBoldIconElement>;
            "django-markdown-field": LocalJSX.DjangoMarkdownField & JSXBase.HTMLAttributes<HTMLDjangoMarkdownFieldElement>;
            "h1-icon": LocalJSX.H1Icon & JSXBase.HTMLAttributes<HTMLH1IconElement>;
            "h2-icon": LocalJSX.H2Icon & JSXBase.HTMLAttributes<HTMLH2IconElement>;
            "h3-icon": LocalJSX.H3Icon & JSXBase.HTMLAttributes<HTMLH3IconElement>;
            "h4-icon": LocalJSX.H4Icon & JSXBase.HTMLAttributes<HTMLH4IconElement>;
            "h5-icon": LocalJSX.H5Icon & JSXBase.HTMLAttributes<HTMLH5IconElement>;
            "h6-icon": LocalJSX.H6Icon & JSXBase.HTMLAttributes<HTMLH6IconElement>;
            "italic-icon": LocalJSX.ItalicIcon & JSXBase.HTMLAttributes<HTMLItalicIconElement>;
            "link-icon": LocalJSX.LinkIcon & JSXBase.HTMLAttributes<HTMLLinkIconElement>;
            "list-icon": LocalJSX.ListIcon & JSXBase.HTMLAttributes<HTMLListIconElement>;
            "list-ordered-icon": LocalJSX.ListOrderedIcon & JSXBase.HTMLAttributes<HTMLListOrderedIconElement>;
            "underline-icon": LocalJSX.UnderlineIcon & JSXBase.HTMLAttributes<HTMLUnderlineIconElement>;
        }
    }
}
