name: CI

on: [push]

permissions:
  contents: write
  pull-requests: write

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: workspace
          path: .

  test-frontend:
    name: Test Frontend
    needs: build-frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: workspace
          path: .
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - run: npm ci
      - run: npm run test

  # merge:
  #   name: Auto-merge Dependabot
  #   runs-on: ubuntu-latest
  #   needs: [test-frontend, test-backend]
  #   if: github.actor == 'dependabot[bot]'
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Enable auto-merge
  #       run: gh pr merge --auto --merge "$PR_URL"
  #       env:
  #         PR_URL: ${{ github.event.pull_request.html_url }}
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Publish Release
    if: startsWith(github.ref, 'refs/tags/')
    needs: [test-frontend, test-backend]
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/project/django-enchanted-markdown-field/  
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Install Hatch
        run: pip install hatch
      - uses: actions/download-artifact@v4
        with:
          name: workspace
          path: .
      - name: Build package
        run: |
          hatch build
      - name: Upload release assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: py-dist/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: py-dist/
